#!/usr/bin/python3
# -*- coding: utf-8 -*-

#
# Блок finally
#

# При обработке исключений также можно использовать 
# необязательный блок finally. Отличительной особенностью 
# этого блока является то, что он выполняется вне 
# зависимости, было ли сгенерировано исключение:

try:
    number = int(input("Введите число: "))
    print("Введенное число:", number)
except ValueError:
    print("Не удалось преобразовать число")
finally:
    print("Блок try завершил выполнение")
print("Завершение программы")

# Как правило, блок finally применяется для освобождения 
# используемых ресурсов, например, для закрытия файлов.