#!/usr/bin/python3
# -*- coding: utf-8 -*-

#
# Получение информации об исключении
#

# С помощью оператора as мы можем передать всю информацию
# об исключении в переменную, которую затем можно и
# спользовать в блоке except:

try:
    number = int(input("Введите число: "))
    print("Введенное число:", number)
except ValueError as e:
    print("Сведения об исключении", e)
print("Завершение программы")
